name: Deploy to Github Pages

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows pushing to the gh-pages branch
      pages: write     # Required for GitHub Pages (if using the pages action)
      id-token: write  # Required for OIDC token (if using the pages action)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Copy CNAME file
        run: cp CNAME ./dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Adjust this path if your build output is in a different directory
          publish_branch: gh-pages # You can change this if needed
